apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  replicas: 3 # You can adjust the number of replicas as needed
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-container
          image: ujjinimech/ujji-cv:v1 # Replace 'latest' with the desired image tag
          ports:
            - containerPort: 80 # Replace with the appropriate port
      imagePullSecrets:
        - name: regcred