name: Docker Image CI

on:
  push:
    branches: [ "main" ]

permissions:
      contents: 'read'
      id-token: 'write'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      
    # - name: Login to GAR
    #   uses: docker/login-action@v2
    #   with:
    #       registry: us-central1-docker.pkg.dev
    #       username: _json_key_base64
    #       password: ${{ secrets.GCLOUD_AUTH }}
          
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag $(date +%s)  
    - name: push to gcr
      uses: raccoondev/push-docker-gcr@v1
      with:
        gcr_host: us-central1-docker.pkg.dev
        image_name: my-practice/my-cv:$(date +%s)
        # image_tag: 
      env:
           GCLOUD_SERVICE_KEY: ${{ secrets.GCLOUD_SERVICE_KEY }}
           GOOGLE_PROJECT_ID: ${{ secrets.GOOGLE_PROJECT_ID }}

# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:

#     - name: code checkout
#       uses: actions/checkout@v2

#     - name: install the gcloud cli
#       uses: google-github-actions/setup-gcloud@v0
#       with:
#         project_id: ${{ secrets.GCLOUD_PROJECT }}
#         service_account_key: ${{ secrets.GCLOUD_AUTH }}
#         export_default_credentials: true

#     - name: build and push the docker image
#       env:
#         GOOGLE_PROJECT: ${{ secrets.GCLOUD_PROJECT }}
#       run: |
#         gcloud auth configure-docker us-central1-docker.pkg.dev
#         docker build -t us-central1-docker.pkg.dev/$GOOGLE_PROJECT/my-practice/my-cv:latest .
#         docker push us-central1-docker.pkg.dev/$GOOGLE_PROJECT/my-practice/my-cv:latest
  # - name: deploy to gke
  #     env:
  #       GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
  #     run: |
  #       gcloud container clusters get-credentials autopilot-cluster-1 --region us-central1
  #       sed -i "s/GOOGLE_PROJECT/$GOOGLE_PROJECT/g" resources.yaml
  #       kubectl apply -f resources.yaml
