name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      
    - name: Login to GCR
      uses: docker/login-action@v2
      with:
          registry: us-central1-docker.pkg.dev
          username: _json_key_base64
          password: ${{ secrets.GCLOUD_AUTH }}
          
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-cv
      
    - name: push to gcr
      uses: raccoondev/push-docker-gcr@v1
      with:
        gcr_host: us-central1-docker.pkg.dev
        image_name:  my-cv
        image_tag: latest
         env:
          GCLOUD_SERVICE_KEY: ${{ secrets.GCLOUD_AUTH }}
          GOOGLE_PROJECT_ID: ${{ secrets.GCLOUD_PROJECT }}
